
import './globals.css'
import type { Metadata } from 'next'
import '@radix-ui/themes/styles.css';
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import NavBar from './NavBar'
import { Toaster } from '@/components/ui/toaster';
import SessionProvider from './Provider';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
        <Theme>
        <NavBar />
        
        //background//
        <main className= 'mt-8 h-auto flex flex-col justify-center items-center'>{children}</main>
        <Toaster />
        </Theme>
        </SessionProvider>
        </body>
    </html>
  )
}
