
import './globals.css'
import type { Metadata } from 'next'
import '@radix-ui/themes/styles.css';
import { Inter } from 'next/font/google'
import { Theme } from '@radix-ui/themes'
import NavBar from './NavBar'
import { Toaster } from '@/components/ui/toaster';
import SessionProvider from './Provider';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <head> 
        <link href="https://fonts.googleapis.com/css2?family=Protest+Strike&display=swap" rel="stylesheet" />
        
      <body className=" justify-center items-center h-screen pt-36">
        <SessionProvider>
        <Theme>
        <NavBar />
        
   
        <main className=  'h-auto flex flex-col justify-center items-center'>{children}</main>
        <Toaster />
        </Theme>
        </SessionProvider>
        </body>
        </head>
    </html>
  )
}
